### ISSUE TITLE
Tome Rater Project Review

### ISSUE THREAD

**Issue by wwang99** [gabriellaquattrone/TomeRater#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_
 
- No errors!

### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_
 
- With functions like ``get_most_read_book``, it is a better practice to return only the value of the most read book or whatever else value the function is supposed to get. Leave the printing out/formatting of the retrieved value to be handled outside the function because you may want to do different things with the value you get from the function depending on the situation. It is a bad practice to return a string representation of the value you want.
- Same thing happens in ``highest_rated_book`` and ``most_positive_user``

### Criteria 3: Software Architecture
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_
 
- Great job commenting your code!
- One thing to watch out for, it is best formatting practice to have a blank line between each function for readability
- For ``User``'s ``__eq__`` function, it's best to just return whether or not they are equal or not. Let whatever uses the equality function to decide how to print out the message and what to do with the information. Same thing with in ``Book``

### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations) 
* _Comment(s):_
 
- Nice job using Python's feature to chain comparison operators here! ``if rating and 0 <= rating <= 4:``

### Overall Score: 14/16

Overall great job with this project! It's important to watch out for the best practices I pointed out above because just returning the desired value from the function makes your program much more flexible! You can do whatever you want with the value you retrieve instead of only returning a string to be printed out.

**Comment by gabriellaquattrone** [comment]
I just fixed all the issues you mentioned! Thank you so much for the helpful advice! I really had fun with this class and hope to take another.
